vich_uploader:
    db_driver: orm
    storage: file_system
    metadata:
        type: attribute
    mappings:
        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true